batch_size: 1024
clip_gradient_norm: 1
clip_targets_to_zero:
- streamflow_mmd
data_dir: /Users/sho108/Desktop/z/Data/CAMELS_AUS
dataset: camels_aus
device: cpu
dynamic_inputs: precipitation_AWAPet_morton_point_SILO
epochs: 30
experiment_name: spatial_twofold_1_PaEm
head: regression
hidden_size: 20
initial_forget_bias: 3
learning_rate:
  0: 0.01
  15: 0.005
log_interval: 5
log_n_figures: 1
log_tensorboard: true
loss: MSE
metrics:
- NSE
- MSE
- RMSE
- KGE
- Alpha-NSE
- Pearson-r
- Beta-KGE
- Beta-NSE
- FHV
- FMS
- FLV
- Peak-Timing
- Missed-Peaks
- Peak-MAPE
model: cudalstm
num_workers: 8
optimizer: Adam
output_activation: linear
output_dropout: 0.4
predict_last_n: 1
save_weights_every: 1
seq_length: 365
target_variables:
- streamflow_mmd
test_basin_file: basins/twofoldsplit/fold_1_test.txt
test_end_date: 31/12/2018
test_start_date: 01/01/1981
train_basin_file: basins/twofoldsplit/fold_1_train.txt
train_end_date: 31/12/2018
train_start_date: 01/01/1981
validate_every: 5
validate_n_random_basins: 10
validation_basin_file: basins/twofoldsplit/fold_1_test.txt
validation_end_date: 31/12/2018
validation_start_date: 01/01/1981
